apiVersion: v1
kind: Service
metadata:
  namespace: kafka
  name: zookeeper
  labels:
    app: zookeeper
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30181
      targetPort: 2181
  selector:
    app: zookeeper
